name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # veya "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - run: echo "No build needed for static HTML" # Static dosyalar için
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./ # Tüm repo içeriğini deploy et
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
